import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const sourceUrl = process.env.IIKO_UPSTREAM_OPENAPI_URL ?? 'https://api-ru.iiko.services/api-docs/docs';
const snapshotPath = resolve(process.cwd(), 'contracts/upstream/iiko-openapi.json');
const sourcePath = resolve(process.cwd(), 'contracts/upstream/SOURCE.md');

function sha256(value: string): string { return createHash('sha256').update(value).digest('hex'); }

async function fetchSnapshot(): Promise<string> {
  const response = await fetch(sourceUrl);
  if (!response.ok) throw new Error(`Upstream fetch failed: HTTP ${response.status}`);
  const text = await response.text();
  JSON.parse(text) as unknown;
  return text;
}

const command = process.argv[2] ?? 'check';
const pinned = await readFile(snapshotPath, 'utf8');
const current = await fetchSnapshot();
const pinnedHash = sha256(pinned);
const currentHash = sha256(current);
if (command === 'check') {
  console.log(JSON.stringify({ sourceUrl, pinnedSha256: pinnedHash, currentSha256: currentHash, drift: pinnedHash !== currentHash }));
  if (pinnedHash !== currentHash) process.exitCode = 1;
} else if (command === 'update') {
  await writeFile(snapshotPath, current, 'utf8');
  await writeFile(sourcePath, `# Upstream snapshot provenance\n\n- origin URL: ${sourceUrl}\n- fetched_at: ${new Date().toISOString()}\n- sha256: ${currentHash}\n- OpenAPI: 3.0.1\n- source version: empty in upstream info.version; embedded DTO references report iiko assembly 9.8.2.2\n- licensing/source notes: unmodified public iikoCloud OpenAPI snapshot; retain upstream terms and do not edit this file manually.\n`, 'utf8');
  console.log(JSON.stringify({ updated: true, sourceUrl, sha256: currentHash }));
} else {
  throw new Error('Usage: upstream.ts check|update');
}
